spring:
  application:
    name: catalog-service
  profiles:
    active: prod
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
server:
  port: 9001
  # tomcat:
  #   threads:
  #     max: 50
  #     min-spare: 5
management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to JamROck
